### PR TITLE
Hugo and docs

### PR DESCRIPTION
**Pull request by akellbl4**
This is the first small effort to add documentation on the site. For a good view of docs, we need to make a proper structure and add frontmatter to our documentation.

When we will make our documentation suitable for generation on site I will make better styling and structuring of styles, now it is just a simple example of how it may look.

* use Hugo for site generation
* add remark42 as a module for sourcing docs
* simple styling for docs

### What else should be done in this PR:

- [ ]  Deploy?
- [ ] Documentation for developers
- [ ] Full styling for docs pages
- [ ] Proper styles structure
- [ ] Banners for latest and old versions in docs

Install dependencies: `yarn`
Run dev-env: `yarn dev`
Run in docker: `docker-compose -f docker-compose.docs.yml up` (please add path to docs in compose file)
@paskal you should be interested in this PR. If you have any problems with styles please write to me.

### CODE REVIEW

**Review by paskal — APPROVED** [review]
LGTM if the menu to the left could have custom names for pages and tree structure.

I think we shouldn't take docs from the release tag from remark42 repo and should instead move them physically to this repo and maintain separately.

image

**Comment by akellbl4** [comment]
Docs by versions was added
Screenshot 2020-04-06 at 11 56 00

**Comment by paskal** [comment]
It's got a few rough edges I can describe in detail if you'll contact me, but generally, the concept looks good.

**Comment by akellbl4** [comment]
@paskal yep, it is the first really simple realization. Of course, It needs to improve before release, also from the documentation side.

**Pull request merged**
